### ISSUE TITLE
wine 7.18 staging

### ISSUE THREAD

**Issue by jg00dman** [ferion11/Wine_Appimage#10]
Any chance you could do a wine 7.18 staging appImage? This would work for Logos 10 / Verbum 10

**Comment by ferion11** [comment]
> Any chance you could do a wine 7.18 staging appImage? This would work for Logos 10 / Verbum 10

WINE with dependency will be hard, because Logos Bible need one WoW64 installation.
But after solve some issues, I will update the Appimage to use the last WINE without deps:
https://github.com/ferion11/wine_WoW64_nodeps_AppImage

**Comment by jg00dman** [comment]
I found this https://github.com/mmtrt/WINE_AppImage/releases/download/continuous-staging/wine-staging_7.18-x86_64.AppImage so no need to duplicate work. Thanks.
