### ISSUE TITLE
I had an error installing a game in battle.net,

### ISSUE THREAD

**Issue by FrostKnight** [ferion11/Wine_Appimage#4]
the game is starcraft and starcraft 2.  I wondered if you could tell me what drivers i need to enable in the wine config to make it work.  

"Because battle.net keeps refusing to install 3/4's of the way giving this bug: Something went wrong with a file. We're not sure what caused it, so please try again or click the code below for more information, Sorry about that!"

Or, if you are still trying to sort out some bugs...

Either way, I was able to log into battle.net, so, good job so far! :) 
PS, the version I used each version but the results I mentioned came form the continuous build.

The other builds failed for me.

**Comment by FrostKnight** [comment]
Also this was an arch based linux distro I used it on.

**Comment by ferion11** [comment]
Well, the compatibility of Wine have many variations with versions change.
There are better ways for your situation. My recommendation is to use your native solution of playonlinux to install it, instead of using the AppImage. Here, the package: https://www.archlinux.org/packages/community/x86_64/playonlinux/
That said, to give an answer, from playonlinux database: https://www.playonlinux.com/en/app-661-Starcraft_II_Wings_of_Liberty.html
we have that the game in question work better with wine-3.19-staging, and battle.net need corefonts and vcrun2015 installed using winetricks. Something like (if you are using the default WINEPREFIX=~/.wine32):
```
$ wget -c https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
$ chmod +x ./winetricks
$ env WINEPREFIX=~/.wine32 sh ./winetricks corefonts vcrun2015
```

**Comment by FrostKnight** [comment]
Hmm, I hadn't realized this, but yeah, same error on debian too with your appimage. If you want ill be patient and wait, but as for whether I can use the archlinux package, that is a no.
Also, my distro might be discontinuing multilib for security reasons. Which is not good for one of my laptops, but for most, yeah.   Just give me an idea how long the wait might be...

Also, tell me, are you guys planning to make an appimage with 64 bit support?  Either way, appreciate that some of this works. :)
ps, the arch based distro is known as Hyperbola.

They do plan to move to BSD though in future, but I imagine that won't change much if appimage can be used there too. Though I have no clear answer yet, I haven't asked. :|
Probably this will happen in 2023.

**Comment by ferion11** [comment]
I understand. Well, in that case you should install `corefonts` and `vcrun2015` like mentioned on my preview answer, before install the `battle.net`.

One AppImage with wine32+wine64 (using WoW64, Windows on Windows64, installation) is very bigger (like ~700MB). It make very big WINEPREFIXs too. And I need to patch the wine source code for this work with AppImage (I don't have multilib too, so I need one better way to build it using remote services). So no plans for WoW64 installation now. By the way, I made one winebottle WoW64 with dotnet4 just to test (compressed it have 568MB): https://github.com/ferion11/wine64_bottle_dotnet/releases

The Kron4ek have portables Wine too, more compressed that works like AppImage. But I don't have tested it yet. Some could be with wine64:
https://github.com/Kron4ek/wine-portable-executable/releases

**Comment by FrostKnight** [comment]
Ah,I will try those, as for corefonts, and vcrun2015 well yeah... I might just do that.

odd thing is, it gets to the last 1.33GB's of the starcraft install and utterly fails. So weird...
so yeah, its like a 1/4th of the install left to go or maybe slightly more.  So bizzare. I will try your suggestion though. :)

I prefer an OS that is as libre as possible by default. Then if I use non-free software, i will use it in a container, as it is more secure that way... :) 

qemu or wine-staging being two examples. heh...

Btw, how do you assign it to a 32 bit appimage? or is it in the appimage as an option already?

**Comment by ferion11** [comment]
No matter what wine installation you use (AppImage or no), it always create a bottle, in this case, at your `$HOME/.wine32`, and inside it, having the directory `drive_c`, where the applications are installed. So, like your game, the `corefonts` and `vcrun2015` will be installed inside your Wine Bottle. The winetricks is one command line util that make the process of installation easier. Then, you can just type the commands:
```
wget -c https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
env WINEPREFIX=~/.wine32 sh ./winetricks corefonts vcrun2015
```
and it will do the job of install `corefonts` and `vcrun2015` inside `$HOME/.wine32`. After that, you can try to install the game again And if you want one cleaner installation, then just remove your wine bottle with `rm -rf $HOME/.wine32` before the installation of `corefonts`, `vcrun2015` and the game.
The official Wine default is 32bit. The 64bit version is the one hard to work with.
Maybe on the future, the opensource https://reactos.org/ will be a better option for Windows games and applications.

**Comment by FrostKnight** [comment]
> No matter what wine installation you use (AppImage or no), it always create a bottle, in this case, at your `$HOME/.wine32`, and inside it, having the directory `drive_c`, where the applications are installed. So, like your game, the `corefonts` and `vcrun2015` will be installed inside your Wine Bottle. The winetricks is one command line util that make the process of installation easier. Then, you can just type the commands:
> 
> ```
> wget -c https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
> env WINEPREFIX=~/.wine32 sh ./winetricks corefonts vcrun2015
> ```
> 
> and it will do the job of install `corefonts` and `vcrun2015` inside `$HOME/.wine32`. After that, you can try to install the game again And if you want one cleaner installation, then just remove your wine bottle with `rm -rf $HOME/.wine32` before the installation of `corefonts`, `vcrun2015` and the game.
> The official Wine default is 32bit. The 64bit version is the one hard to work with.
> Maybe on the future, the opensource https://reactos.org/ will be a better option for Windows games and applications.

Just one thought occurs to me, I keep getting some weird errors, no such file or directory...

I just checked too and winetricks is being made in a rather odd way lately:

This option is not available. Please see --help for all possible usages.
------------------------------------------------------
/tmp/wine-portable-5.12-staging-amd64.sh_user_3224/mnt/wine/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "/tmp/wine-portable-5.12-staging-amd64.sh_user_3224/mnt/winetricks: line 3383: /tmp/wine-portable-5.12-staging-amd64.sh_user_3224/mnt/wine/bin/wine: No such file or directory" 
------------------------------------------------------

**Comment by FrostKnight** [comment]
that bug happened when I tried using this: ./wine-portable-5.12-staging-amd64.sh winetricks --gui

edit: So yeah, unless you have another solution, I might just be better off waiting to do anything else. :/

aka, moving all my operating systems away to Hyperbola. ;)

**Comment by ferion11** [comment]
Well, you should use what is more comfortable to you.
I don't know how the wine-portable from Kron4ek works, but with AppImage it works normal. I use winetricks a lot in my tests and scripts here (like in my [LogosLinuxInstaller](https://github.com/ferion11/LogosLinuxInstaller) and the automatized tests for it like [this one](https://travis-ci.com/github/ferion11/LogosLinuxInstallTests/jobs/366809325)).
Using the AppImage, you should just make the links on your bin directory and use, like the instructions on the [README](https://github.com/ferion11/Wine_Appimage/blob/master/README.md). Like, just to give you the full picture of commands:
```
rm -rf $HOME/.wine32
cd $HOME
mkdir AppImage
cd AppImage
wget -c https://github.com/ferion11/Wine_Appimage/releases/download/v5.11/wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage
chmod +x wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage
cd $HOME
mkdir bin
cd bin
ln -s ../AppImage/wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage wine
ln -s ../AppImage/wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage wineserver
echo export PATH=\$HOME/bin:\$PATH >> $HOME/.bashrc
source $HOME/.bashrc
wget -c https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
env WINEPREFIX=~/.wine32 sh ./winetricks corefonts vcrun2015
```
After that, the next time you need wine, you can just use the command `wine` (because it will be in your `$PATH` variable, like any installed package), or `env WINEPREFIX=~/.wine32 sh ./winetricks` for winetricks GUI.

**Comment by FrostKnight** [comment]
> Well, you should use what is more comfortable to you.
> I don't know how the wine-portable from Kron4ek works, but with AppImage it works normal. I use winetricks a lot in my tests and scripts here (like in my [LogosLinuxInstaller](https://github.com/ferion11/LogosLinuxInstaller) and the automatized tests for it like [this one](https://travis-ci.com/github/ferion11/LogosLinuxInstallTests/jobs/366809325)).
> Using the AppImage, you should just make the links on your bin directory and use, like the instructions on the [README](https://github.com/ferion11/Wine_Appimage/blob/master/README.md). Like, just to give you the full picture of commands:
> 
> ```
> rm -rf $HOME/.wine32
> cd $HOME
> mkdir AppImage
> cd AppImage
> wget -c https://github.com/ferion11/Wine_Appimage/releases/download/v5.11/wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage
> chmod +x wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage
> cd $HOME
> mkdir bin
> cd bin
> ln -s ../AppImage/wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage wine
> ln -s ../AppImage/wine-staging-linux-x86-v5.11-PlayOnLinux-x86_64.AppImage wineserver
> echo export PATH=\$HOME/bin:\$PATH >> $HOME/.bashrc
> source $HOME/.bashrc
> wget -c https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
> env WINEPREFIX=~/.wine32 sh ./winetricks corefonts vcrun2015
> ```
> 
> After that, the next time you need wine, you can just use the command `wine` (because it will be in your `$PATH` variable, like any installed package), or `env WINEPREFIX=~/.wine32 sh ./winetricks` for winetricks GUI.

Appreciate you making it easier for me to understand, am trying it now. 

Will let you know the result...

Heh, same result, I wonder if its because its based on too old of a wine-staging version...

I have been able to get things running on wine-staging 5.16+

**Comment by ferion11** [comment]
> Heh, same result, I wonder if its because its based on too old of a wine-staging version...
> 
> I have been able to get things running on wine-staging 5.16+

No. You are just using it the wrong way (this type of procedure has already been extensively tested, using automated tests). The requirements for this game is wine-staging-3.19, and today the last official stable version is Wine-5.0.1 at https://www.winehq.org.

In order to not turn this issue into a basic linux tutorial, I'll be brief on some recommendations:
I recommend you to use some linux distribution that have multilib support and the GUI for install wine games, like PlayOnLinux, Lutris, Steam, ..., while you learn how linux works first (because without it, without this experience, will be hard to use not only wine). Or, if you don't want to learn linux, you can use the https://reactos.org that is one Windows opensouce implementation (the Windows application compatibility is better than using Wine).

Nobody starts on linux with all the knowledge, so start using it for simple applications, and gradually understand how it works, in your own pace. You can try to read some guides from [The Linux Documentation Project](https://www.tldp.org/) too.

**Comment by FrostKnight** [comment]
My bad, close this issue if you want, I clearly am missing something and I apologize for wasting your time.

Actually, I will close this if for now, feel free to open if you wish again.

**Comment by ferion11** [comment]
> My bad, close this issue if you want, I clearly am missing something and I apologize for wasting your time.
> 
> Actually, I will close this if for now, feel free to open if you wish again.

Don't worry, I just don't want to deviate from the topic of the issue.
There are better places to discuss this type of basic usage, such as the Linux distribution forums.
I myself have join the Gentoo one here: http://forums.gentoo.org
I don't know what distribution you are using, but it is very worthwhile to participate in its forum, as many of the situations need easier solutions to use that are implemented by the users who read and answer the questions there.

**Comment by FrostKnight** [comment]
Good news, your proton appimage actually allows me to finish the install that was otherwise impossible with the newer version. Aka, this:

https://github.com/ferion11/Proton_Appimage/releases

I tried it just now and it worked in installing the game.

Although, i should add it worked on my debian, going to try it on Hyperbola now. 

Although just an edit, it doesnt quite work in playing game, but yeah, thats all for now.  I am sure sooner or later you will get it mostly working. Thanks though! :)
