### ISSUE TITLE
Can it run both 64bit and 32bit Apps

### ISSUE THREAD

**Issue by thenoobtester** [ferion11/Wine_Appimage#5]
Hi,

at the risk of sounding stupid if the answer is obvious, is it possible to run both 64 bit and 32 bit Windows apps with this Appimage? I ask because it says it can run on "no multilib systems" which I interpret as it's meant for multilib systems but if you don't run on one you're fine too.

If not, is there such a Wine Appimage which allows running both 64 bit and 32 bit windows apps?

Thank you for your help

EDIT: I think I'm confused about what multilib means. It means you can run the 32bt Wine on a 64bit Linux OS, right ? What I'm looking for is an Appimage which would run on a 64bit Linux (Debian in my case) and be able to run both 32bit and 64bit Windows apps.

**Comment by ferion11** [comment]
Well, this AppImage was made to run Windows 32bit applications.
There is a version that can run both using WINE WOW64:
https://github.com/ferion11/wine_WoW64_nodeps_AppImage/releases
but I'm not including the dependencies (like winbind, cabextract, libjpeg8, ... 32bits and 64bits versions), as it would make the file very large (about 1GB in my estimate). Besides the fact that working with two different glibc (32bits and 64bits) in the same WINE AppImage is still a complicated task to be done.

**Comment by ferion11** [comment]
> EDIT: I think I'm confused about what multilib means. It means you can run the 32bt Wine on a 64bit Linux OS, right ? What I'm looking for is an Appimage which would run on a 64bit Linux (Debian in my case) and be able to run both 32bit and 64bit Windows apps.

https://wiki.gentoo.org/wiki/Multilib

**Comment by thenoobtester** [comment]
Sorry for the delay (boring long personal story), thank you for the response, link and explanations.
