### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by lucasmz1** [ferion11/Wine_Appimage#9]
hi how can I find you? I am trying to pack my own wine can you help me ?

**Comment by ferion11** [comment]
To pack your own WINE, you need to use the appimagetool (and install WINE and deps on one directory).
You can see how it's done on:

* Arch Linux:
https://github.com/ferion11/Wine_Appimage/blob/master/deployscript/archlinux-wine-deploy.sh
or
https://github.com/Hackerl/Wine_Appimage/blob/master/deployscript/arch-winedeploy.sh

* Debian:
https://github.com/Hackerl/Wine_Appimage/blob/master/deployscript/debian-winedeploy.sh

* Open Suse:
* https://github.com/Hackerl/Wine_Appimage/blob/master/deployscript/opensuse-winedeploy.sh

The idea is the same in all options: 1- Install WINE e deps on one directory, 2- Create one script AppRun that will run the installation, 3- And use the appimagetool to pack it.
